graphql:
  servlet:
    actuator-metrics: true
    mapping: /graphql
    enabled: true
    corsEnabled: true
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    schema-location-pattern: "**/*.graphqls"
server:
  port: 8000

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"
